name: Train and Deploy MLflow Model

on:
  push:
    branches:
      - main
    paths:
      - 'MLproject/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  train-model:
    runs-on: ubuntu-latest

    env:
      MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      USERNAME: ${{ secrets.DOCKER_USERNAME }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      - name: Install MLflow CLI (if not in base env)
        run: |
          python -m pip install --upgrade pip
          pip install mlflow # Hanya perlu menginstal CLI MLflow di base environment

      - name: Run MLflow Project
        working-directory: ./MLproject
        run: |
          # MLflow akan membaca conda.yaml dan membangun/menggunakan lingkungan yang benar
          mlflow run . -e train_lr_model -P data_path="personality_preprocessing/namadataset_processed_full.csv" -P lr_c=0.1 -P lr_penalty=l2 --run-name "CI_Automated_LR_Deploy" --env-manager=conda

      # --- Langkah-langkah selanjutnya tetap sama ---
      - name: Upload MLflow Runs as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-runs-local-copy
          path: MLproject/mlruns/
          retention-days: 7

      - name: Get latest RUN_ID
        id: get_run_id
        working-directory: MLproject
        run: |
          RUN_ID=$(ls -Art mlruns/0/runs/ | tail -n 1)
          echo "Latest RUN_ID: $RUN_ID"
          echo "RUN_ID=$RUN_ID" >> $GITHUB_OUTPUT

      - name: Copy model artifact for Git/Docker
        run: |
          mkdir -p artifact_model_storage_Terbaru_dari_github_actions
          cp -r MLproject/mlruns/0/runs/${{ steps.get_run_id.outputs.RUN_ID }}/artifacts/logistic_regression_model/* artifact_model_storage_Terbaru_dari_github_actions/

      - name: Commit and Push model artifact to Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add artifact_model_storage_Terbaru_dari_github_actions/
          git commit -m "Automated: Add latest trained model artifact from run ${{ steps.get_run_id.outputs.RUN_ID }}" || echo "Nothing to commit"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push origin HEAD:${{ github.ref_name }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME="${{ secrets.USERNAME }}/personality-classifier-model:latest"
          echo "Building Docker image from MLflow model..."
          mlflow models build-docker -m artifact_model_storage_Terbaru_dari_github_actions/ -n $IMAGE_NAME
          echo "Pushing image to Docker Hub..."
          docker push $IMAGE_NAME
