name: ML Model CI and Docker Build

on:
  push:
    branches:
      - main
    paths:
      - 'MLproject/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./MLproject

    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v4

      - name: 2. Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.7

      - name: 3. Install Conda and Dependencies
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.12.7
          environment-file: MLproject/conda.yaml
          activate-environment: personality_project_env

      - name: 4. Install MLflow
        shell: bash -l {0}
        run: pip install mlflow=2.19.0

      - name: 5. Run MLflow Project (Train Model)
        shell: bash -l {0}
        run: mlflow run . --experiment-name "CI-CD-Personality-Prediction"

      - name: 6. Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 7. Build and Push Docker Image with MLflow
        shell: bash -l {0}
        run: |
          RUN_ID=$(cat run_id.txt)
          echo "Using MLflow Run ID: $RUN_ID"

          mlflow models build-docker \
            --model-uri "runs:/${RUN_ID}/logistic_regression_model" \
            --name "bimoadebudimanfikri/personality-classifier" \
            --push

      - name: 8. Upload MLflow Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts-${{ github.run_id }}
          path: |
            MLproject/mlruns
            MLproject/run_id.txt
